# Generated by Django 5.0.4 on 2024-04-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihakiralama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇ha',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kiralanan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
